# Generated by Django 6.0.6 on 2026-06-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price_tag",
            field=models.CharField(blank=True, default="per item", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="technical_specifications",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
