# Generated by Django 6.0.6 on 2026-06-29 14:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="deleted_by_cascade",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="deleted_by_cascade",
        ),
    ]
