# Generated by Django 6.0.6 on 2026-07-03 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_seed_payment_methods"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
    ]
