# Generated by Django 6.0.6 on 2026-06-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_remove_address_profile_address_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("MANAGER", "Manager"), ("CUSTOMER", "Customer")],
                default="CUSTOMER",
                max_length=20,
            ),  # noqa: E501
        ),
    ]
