# Generated by Django 6.0.6 on 2026-07-01 11:56

import operator
from functools import reduce

# from django.contrib.auth.models import Permission
from django.db import migrations
from django.db.models import Q


def create_roles_and_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    manager_group, _ = Group.objects.get_or_create(name="Managers")

    manager_permissions = {
        "accounts": ["view_user", "view_profile", "view_address"],
        "orders": [
            "view_cart",
            "view_cartitem",
            "view_order",
            "change_order",
            "view_orderitem",
            "change_orderitem",
            "view_payment",
            "view_paymentmethod",
        ],
        "products": None,  # All permissions for products app
        "reviews": None,  # All permissions for reviews app
    }

    q_objects = []
    for app, perms in manager_permissions.items():
        if perms is None:
            q_objects.append(Q(content_type__app_label=app))
        else:
            q_objects.append(Q(content_type__app_label=app, codename__in=perms))

    query_filter = reduce(operator.or_, q_objects)
    manager_perms = Permission.objects.filter(query_filter)

    manager_group.permissions.set(manager_perms)


def remove_roles(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["Managers"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_user_role"),
    ]

    operations = [
        migrations.RunPython(create_roles_and_permissions, remove_roles),
    ]
