services:
  nginx:
    volumes:
      - ./logs/prod/nginx:/var/log/nginx

  app:
    build:
      context: .
      target: production
    volumes:
      - ./logs/prod:/app/logs


volumes:
  pg_data:
    name: ai_tg_postgres_prod_data
  pgadmin_data:
    name: ai_tg_pgadmin_prod_data
