services:
  nginx:
    volumes:
      - ./logs/dev/nginx:/var/log/nginx
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build:
      context: .
      target: development
    restart: on-failure
    command: >
      sh -c "uv run manage.py migrate &&
             uv run manage.py setup_admin && 
             uv run python -m debugpy --listen 0.0.0.0:5678 -m manage runserver 0.0.0.0:8000"
    ports:
      # - "8000:8000" # django app
      - "5678:5678" # debugpy
    environment:
      - LOG_FILE=/app/logs/api.log

    healthcheck:
      disable: true

    # Run as root during development so the environment is mutable
    # Alternatively, you could set `UV_PROJECT_ENVIRONMENT` to a path owned by the non-root user
    user: root

    volumes:
      - ./logs/dev:/app/logs
      - /app/.venv/
      - /root/.cache/uv/

    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: ./apps
          target: /app/apps
        - action: sync
          path: ./core
          target: /app/core
        - action: sync
          path: ./static
          target: /app/static
        - action: sync
          path: ./templates
          target: /app/templates
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  postgres:
    environment:
      - POSTGRES_INITDB_ARGS=--username=${POSTGRES_USER}
    ports:
      - "5433:5432"

volumes:
  pg_data:
    name: django_shop_postgres_dev_data
  pgadmin_data:
    name: django_shop_pgadmin_dev_data
